"""
chief_focus_reporter.py

Read-only end-of-day digest for the Focus & Approvals Trinity domain.

Complements:
  - chief_focus_shield.py: holds non-urgent work during focus blocks
  - chief_approval_bridge.py: tracks non-blocking choice prompts

Triggered manually or by CLI for now. It does not approve, deny, surface, or mutate
held items; it only summarizes current focus/approval state and writes a vault note.
"""

import json
from datetime import datetime
from pathlib import Path

HELD_JSON = Path("/mnt/c/OpenClawShared/album/focus_held.json")
CHOICE_PENDING_JSON = Path("/mnt/c/OpenClawShared/album/choice_pending.json")
APPROVAL_PENDING_JSON = Path("/mnt/c/OpenClaw/logs/approval_pending.json")
DIGEST_MD = Path("/mnt/c/OpenClawShared/openclaw-vault/System/Focus Approval Digest.md")


def _read_json(path: Path, default):
    try:
        if path.exists():
            return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        pass
    return default


def _held_items() -> list[dict]:
    data = _read_json(HELD_JSON, [])
    return data if isinstance(data, list) else []


def _pending_state(path: Path) -> dict:
    data = _read_json(path, {})
    return data if isinstance(data, dict) else {}


def _count_held_by_timing(items: list[dict]) -> dict[str, int]:
    counts: dict[str, int] = {}
    for item in items:
        if item.get("surfaced"):
            continue
        timing = str(item.get("shield_timing") or item.get("timing_class") or "unknown")
        counts[timing] = counts.get(timing, 0) + 1
    return counts


def build_digest() -> str:
    held = _held_items()
    unsurfaced = [item for item in held if not item.get("surfaced")]
    held_counts = _count_held_by_timing(held)
    choice = _pending_state(CHOICE_PENDING_JSON)
    approval = _pending_state(APPROVAL_PENDING_JSON)

    choice_status = choice.get("status") or "none"
    approval_status = approval.get("status") or "none"
    approval_action = approval.get("action") or approval.get("capability") or ""

    lines = [
        f"Focus & Approvals Digest — {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        f"Held items: {len(unsurfaced)} unsurfaced",
    ]
    if held_counts:
        lines.append("Held by timing: " + ", ".join(f"{k}={v}" for k, v in sorted(held_counts.items())))
    else:
        lines.append("Held by timing: none")

    lines.extend([
        f"Choice bridge: {choice_status}",
        f"Guardian approval: {approval_status}" + (f" — {approval_action}" if approval_action else ""),
    ])

    if unsurfaced:
        lines.append("Latest held:")
        for item in unsurfaced[-5:]:
            lines.append(f"  - {item.get('id', 'unknown')}: {item.get('title', '—')}")

    return "\n".join(lines)


def _write_digest_md(digest: str) -> None:
    DIGEST_MD.parent.mkdir(parents=True, exist_ok=True)
    content = (
        "---\n"
        "type: focus-approval-digest\n"
        f"last_updated: {datetime.now().strftime('%Y-%m-%d %H:%M')}\n"
        "---\n\n"
        "# Focus & Approvals Digest\n\n"
        "_Generated by `chief_focus_reporter.py`._\n\n"
        f"```\n{digest}\n```\n"
    )
    DIGEST_MD.write_text(content, encoding="utf-8")


def handle(text: str = "") -> list[str]:
    digest = build_digest()
    _write_digest_md(digest)
    return [digest]


if __name__ == "__main__":
    for line in handle():
        print(line)
