#!/usr/bin/env python3
"""dashboard_gen.py — Unified dashboard generator for OpenClaw VS Code windows.

Generates markdown files in /home/openclaw/mac_eyes/ every INTERVAL seconds:
  - For Winship 1 - Right Now.md   (loop status overview)
  - For Winship 2 - What Happened.md (activity log)
  - Cassandra.md                    (Cassandra status, capabilities, messages)
  - Chief.md                        (Chief process status, workers)
  - Guardian.md                     (approval status, pending, history)
  - Big Picture.md                  (system-wide overview)
  - Autonomy Qualification.md       (generated by autonomy_qualification.py)

Run: python3 dashboard_gen.py
"""

import json
import os
import re
import subprocess
import time
from datetime import datetime, timedelta
from pathlib import Path

# ── Paths ─────────────────────────────────────────────────────────────────────

OUT_DIR = Path("/home/openclaw/mac_eyes")
STATUS_FILE = Path("/home/openclaw/polish_loop/status.json")
ORCH_LOG = Path("/mnt/c/OpenClaw/logs/orchestrator.log")
TASKS_DIR = Path("/home/openclaw/polish_loop/tasks")
ARCHIVE_DIR = Path("/home/openclaw/polish_loop/archive")
TASK_FILE = Path("/home/openclaw/polish_loop/task.md")
CURRENT_TASK_FILE = Path("/home/openclaw/polish_loop/current/task.md")
CASSANDRA_STATE = Path("/mnt/c/OpenClaw/logs/cassandra_state.json")
CAPABILITY_FILE = Path("/home/openclaw/cassandra_capability.py")
CONTACT_NICKNAMES = Path("/home/openclaw/contact_nicknames.json")
APPROVAL_PENDING = Path("/mnt/c/OpenClaw/logs/approval_pending.json")
FOLLOWUP_LOG = Path("/mnt/c/OpenClaw/logs/cassandra_followup.jsonl")
CONVERSATIONS_LOG = Path("/mnt/c/OpenClaw/logs/cassandra_conversations.jsonl")
BUDGET_TRACKER = Path("/home/openclaw/budget_tracker.py")
AUTONOMY_QUAL = Path("/home/openclaw/autonomy_qualification.py")

INTERVAL = 30  # seconds

# ── Helpers ───────────────────────────────────────────────────────────────────

def load_json(path: Path) -> dict:
    try:
        return json.loads(path.read_text(encoding="utf-8", errors="ignore"))
    except Exception:
        return {}


def load_jsonl(path: Path) -> list[dict]:
    records = []
    try:
        for line in path.read_text(encoding="utf-8", errors="ignore").splitlines():
            if line.strip():
                records.append(json.loads(line))
    except Exception:
        pass
    return records


def now_str() -> str:
    return datetime.now().strftime("%Y-%m-%d %H:%M:%S")


def age_str(ts_str: str) -> str:
    """Human-readable age from a timestamp string."""
    for fmt in ("%Y-%m-%dT%H:%M:%S.%f", "%Y-%m-%dT%H:%M:%S", "%Y-%m-%d %H:%M:%S"):
        try:
            dt = datetime.strptime(ts_str, fmt)
            delta = datetime.now() - dt
            if delta.total_seconds() < 60:
                return "just now"
            if delta.total_seconds() < 3600:
                return f"{int(delta.total_seconds() / 60)}m ago"
            if delta.total_seconds() < 86400:
                return f"{int(delta.total_seconds() / 3600)}h ago"
            return f"{delta.days}d ago"
        except ValueError:
            continue
    return ts_str


def get_processes() -> dict[str, list[dict]]:
    """Get running OpenClaw processes grouped by subsystem."""
    result = {"cassandra": [], "chief": [], "guardian": [], "builder": [], "other": []}
    try:
        out = subprocess.check_output(
            ["ps", "aux"], text=True, timeout=5
        )
        for line in out.splitlines():
            if "openclaw" not in line:
                continue
            lower = line.lower()
            info = {"line": line.strip(), "pid": line.split()[1] if len(line.split()) > 1 else "?"}
            if "cassandra" in lower:
                result["cassandra"].append(info)
            elif "guardian" in lower:
                result["guardian"].append(info)
            elif "chief" in lower:
                result["chief"].append(info)
            elif "builder" in lower or "builder_watcher" in lower:
                result["builder"].append(info)
            elif "ollama" in lower or "orchestrator" in lower or "dashboard" in lower:
                result["other"].append(info)
    except Exception:
        pass
    return result


def get_capability_flags() -> dict[str, bool]:
    """Read capability flags from cassandra_capability.py."""
    flags = {}
    try:
        text = CAPABILITY_FILE.read_text(encoding="utf-8")
        for line in text.splitlines():
            line = line.strip()
            if line.startswith("#") or "=" not in line:
                continue
            parts = line.split("=", 1)
            name = parts[0].strip()
            val = parts[1].split("#")[0].strip()
            if name.endswith("_CONNECTED") and val in ("True", "False"):
                flags[name] = val == "True"
    except Exception:
        pass
    return flags


def get_queued_tasks() -> list[str]:
    try:
        return sorted(p.stem for p in TASKS_DIR.glob("*.md"))
    except Exception:
        return []


def get_archive_count() -> int:
    try:
        return len(list(ARCHIVE_DIR.glob("*")))
    except Exception:
        return 0


def get_budget_status() -> str:
    try:
        out = subprocess.check_output(
            ["python3", str(BUDGET_TRACKER), "--status"],
            text=True, timeout=10, cwd="/home/openclaw"
        )
        return out.strip()
    except Exception:
        return "Budget tracker unavailable"


def get_orch_log_tail(lines: int = 30) -> list[str]:
    try:
        all_lines = ORCH_LOG.read_text(encoding="utf-8", errors="ignore").splitlines()
        return all_lines[-lines:]
    except Exception:
        return []


def get_task_info() -> tuple[str, str]:
    """Return (task_name, goal) from current task file."""
    for path in [TASK_FILE, CURRENT_TASK_FILE]:
        try:
            text = path.read_text(encoding="utf-8", errors="ignore")
            name = goal = ""
            for line in text.splitlines():
                if line.lower().startswith("title:"):
                    name = line.split(":", 1)[1].strip()
                elif line.lower().startswith("goal:"):
                    goal = line.split(":", 1)[1].strip()
            if name:
                return name, goal
        except Exception:
            continue
    return "", ""


# ── Status translations ──────────────────────────────────────────────────────

STATUS_EXPLAIN = {
    "idle": "Waiting for the next task to begin",
    "pc_turn": "The AI builder is writing code right now",
    "mac_turn": "Builder finished — waiting for Planner to review",
    "approved": "Work approved — tidying up before next task",
    "blocked": "Something went wrong and needs attention",
    "parked": "Builder timed out — needs investigation",
}

STATUS_ICON = {
    "idle": "⬜", "pc_turn": "⏳", "mac_turn": "🔄",
    "approved": "✅", "blocked": "🚨", "parked": "💤",
}

STATUS_NEXT = {
    "idle": "The loop will pick up the next queued task.",
    "pc_turn": "Builder finishes → output → review.",
    "mac_turn": "Planner reviews → approve or rework.",
    "approved": "Archive task → reset → pick up next.",
    "blocked": "Check reason below — may need manual unblock.",
    "parked": "Builder stopped. Ask Copilot to investigate.",
}

LOG_TRANSLATIONS = {
    "idle → pc_turn": "▶ **Task started** — builder launched",
    "pc_turn → mac_turn": "📤 **Builder finished** — sent to review",
    "mac_turn → approved (auto)": "✅ **Auto-approved**",
    "mac_turn → approved": "✅ **Review passed** — task approved",
    "approved → idle": "♻️ **Task complete** — loop reset",
    "idle → blocked": "🚨 **Blocked on idle**",
    "pc_turn → blocked": "🚨 **Builder had a problem**",
    "mac_turn → blocked": "🚨 **Review had a problem**",
    "pc_turn → parked": "💤 **Builder timed out**",
    "mac_turn → pc_turn": "🔁 **Needs rework** — sent back to builder",
}


def translate_log_line(line: str) -> str:
    for pattern, translation in LOG_TRANSLATIONS.items():
        if pattern in line:
            # Extract timestamp
            ts_match = re.search(r"\[(\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2})\]", line)
            ts = ts_match.group(1) if ts_match else ""
            return f"- {ts} {translation}"
    return ""


# ── Generators ────────────────────────────────────────────────────────────────

def get_runner_settings() -> dict:
    """Get current planner and builder runner profiles."""
    settings = {"planner": None, "builder": None}
    try:
        # Read task text for context-aware profile
        task_text = ""
        for path in [TASK_FILE, CURRENT_TASK_FILE]:
            try:
                task_text = path.read_text(encoding="utf-8", errors="ignore")
                if task_text.strip():
                    break
            except Exception:
                continue

        import runner_profiles
        settings["planner"] = runner_profiles.select_profile(task_text, planner_mode=True)
        settings["builder"] = runner_profiles.select_profile(task_text, planner_mode=False)
    except Exception:
        pass
    return settings


def gen_right_now() -> str:
    """Generate 'For Winship 1 - Right Now.md'."""
    status = load_json(STATUS_FILE)
    state = status.get("status", "unknown")
    task_name = status.get("task_name", "—")
    block_reason = status.get("block_reason")
    parked_reason = status.get("parked_reason")
    pass_num = status.get("pass", 1)
    updated = status.get("last_updated", "")

    icon = STATUS_ICON.get(state, "❓")
    explain = STATUS_EXPLAIN.get(state, "Unknown state")
    next_step = STATUS_NEXT.get(state, "Check status.json")
    task_title, task_goal = get_task_info()
    queued = get_queued_tasks()

    lines = [
        f"# {icon} Loop Status — Right Now",
        f"*Updated: {now_str()}*",
        "",
        f"**Status:** {state} — {explain}",
        f"**Last task:** {task_name} (pass {pass_num})",
    ]

    if updated:
        lines.append(f"**Last change:** {age_str(updated)}")

    if block_reason:
        lines.append(f"**⚠️ Blocked:** {block_reason}")
    if parked_reason:
        lines.append(f"**💤 Parked:** {parked_reason}")

    if task_title:
        lines.extend(["", f"### Current Task: {task_title}"])
        if task_goal:
            lines.append(f"> {task_goal}")

    # Active runner settings
    rs = get_runner_settings()
    lines.extend(["", "### Active Runner Settings"])
    for role in ["planner", "builder"]:
        p = rs.get(role)
        if p:
            runner = p.get("runner", "?")
            model = p.get("model", "?")
            tier = p.get("tier", "?")
            budget = f"{float(p.get('budget', 0)):.2f}"
            effort = p.get("effort", "?")
            defer = p.get("defer", False)
            defer_tag = " ⚠️ DEFERRED" if defer else ""
            lines.append(f"- **{role.title()}:** {runner}/{model} · tier={tier} · effort={effort} · budget=${budget}{defer_tag}")
        else:
            lines.append(f"- **{role.title()}:** unavailable")

    lines.extend([
        "", "### What happens next",
        next_step,
        "", f"### Task Queue ({len(queued)} waiting)",
    ])
    if queued:
        for t in queued[:10]:
            lines.append(f"- {t}")
        if len(queued) > 10:
            lines.append(f"- ... and {len(queued) - 10} more")
    else:
        lines.append("*No tasks queued*")

    lines.extend([
        "", f"### Completed Tasks",
        f"**{get_archive_count()}** tasks completed in archive",
    ])

    return "\n".join(lines) + "\n"


def gen_what_happened() -> str:
    """Generate 'For Winship 2 - What Happened.md'."""
    lines = [
        "# What Happened — Activity Log",
        f"*Updated: {now_str()}*",
        "",
    ]

    log_lines = get_orch_log_tail(100)
    translated = []
    for raw in log_lines:
        t = translate_log_line(raw)
        if t:
            translated.append(t)

    if translated:
        lines.append("### Recent Loop Activity")
        lines.extend(translated[-30:])  # Last 30 translated events
    else:
        lines.append("*No recent loop activity to show.*")

    return "\n".join(lines) + "\n"


def gen_cassandra() -> str:
    """Generate 'Cassandra.md' — Cassandra status dashboard."""
    state = load_json(CASSANDRA_STATE)
    flags = get_capability_flags()
    procs = get_processes()
    nicknames = load_json(CONTACT_NICKNAMES)
    followups = load_jsonl(FOLLOWUP_LOG)

    lines = [
        "# 🔮 Cassandra — Status Dashboard",
        f"*Updated: {now_str()}*",
        "",
    ]

    # Process status
    cas_procs = procs.get("cassandra", [])
    lines.append("### Processes")
    if cas_procs:
        for p in cas_procs:
            pid = p["pid"]
            cmd = p["line"].split("/")[-1][:60] if "/" in p["line"] else p["line"][:60]
            lines.append(f"- ✅ PID {pid}: `{cmd}`")
    else:
        lines.append("- ❌ No Cassandra processes running!")

    # Capabilities
    lines.extend(["", "### Capabilities"])
    for name, connected in sorted(flags.items()):
        icon = "✅" if connected else "❌"
        lines.append(f"- {icon} {name}: {'Connected' if connected else 'Not connected'}")

    # Last interaction
    last_interaction = state.get("last_interaction_at", "N/A")
    lines.extend([
        "", "### Last Activity",
        f"- Last interaction: {last_interaction} ({age_str(last_interaction) if last_interaction != 'N/A' else 'N/A'})",
    ])

    # Chirp log
    chirps = state.get("chirp_log", [])
    if chirps:
        lines.extend(["", f"### Chirp Log ({len(chirps)} entries)"])
        for c in chirps[-5:]:
            lines.append(f"- {c.get('type', '?')} at {c.get('at', '?')}")

    # Contacts
    lines.extend(["", "### Contacts"])
    placeholder_count = 0
    for nick, data in nicknames.items():
        if nick.startswith("_"):
            continue
        name = data.get("name", str(data)) if isinstance(data, dict) else str(data)
        is_placeholder = "PLACEHOLDER" in str(name)
        if is_placeholder:
            placeholder_count += 1
        icon = "⚠️" if is_placeholder else "✅"
        lines.append(f"- {icon} {nick}: {name[:40]}")
    if placeholder_count:
        lines.append(f"\n**⚠️ {placeholder_count} contacts still have PLACEHOLDER names — outreach blocked**")

    # Follow-ups
    if followups:
        lines.extend(["", f"### Follow-up Queue ({len(followups)})"])
        for f in followups[-5:]:
            lines.append(f"- {f.get('capability', '?')}: {f.get('status', '?')}")

    # Queued Cassandra upgrade tasks
    cas_tasks = [t for t in get_queued_tasks() if t.startswith("cas-")]
    if cas_tasks:
        lines.extend(["", f"### Queued Upgrade Tasks ({len(cas_tasks)})"])
        for t in cas_tasks:
            lines.append(f"- 📋 {t}")

    # Recent conversations — show wins (routed) and fails (error/unrouted) separately
    convos = load_jsonl(CONVERSATIONS_LOG)
    if convos:
        wins = [c for c in convos if c.get("route") not in ("llm", "llm_deep", "error")]
        fallbacks = [c for c in convos if c.get("route") in ("llm", "llm_deep")]
        errors = [c for c in convos if c.get("route") == "error"]
        recent = convos[-10:]
        lines.extend(["", f"### Recent Messages ({len(convos)} total — {len(wins)} routed, {len(fallbacks)} unrouted, {len(errors)} errors)"])
        for c in reversed(recent):
            ts = c.get("ts", "?")
            user_msg = c.get("user", "")[:80]
            route = c.get("route", "?")
            replies = c.get("replies", [])
            reply_preview = replies[0][:80] if replies else ""
            # Visual distinction: routed=✅, unrouted=⚠️, error=❌
            if route in ("llm", "llm_deep"):
                route_icon = "⚠️"
                route_label = f"unrouted ({route})"
            elif route == "error":
                route_icon = "❌"
                route_label = "error"
            else:
                route_icon = "✅"
                route_label = route
            lines.extend([
                f"- **{ts}** {route_icon} [{route_label}]",
                f"  - 👤 {user_msg}",
                f"  - 🔮 {reply_preview}",
            ])

    # Briefing delivery failures (PENDING in briefing_log.md)
    briefing_log = Path("/mnt/c/OpenClaw/logs/cassandra_briefings/briefing_log.md")
    if briefing_log.exists():
        try:
            log_lines = briefing_log.read_text().splitlines()
            pending = [l for l in log_lines if "/PENDING]" in l]
            delivered = [l for l in log_lines if "/delivered]" in l]
            failed_llm = [l for l in log_lines if "LLM did not respond" in l or "unavailable" in l.lower()]
            if pending or failed_llm:
                lines.extend(["", f"### Briefing Delivery Issues"])
                lines.append(f"- Total generated: {len(pending) + len(delivered)}")
                lines.append(f"- Delivered (Telegram): {len(delivered)}")
                lines.append(f"- PENDING (not delivered): {len(pending)}")
                if failed_llm:
                    lines.append(f"- LLM failures during generation: {len(failed_llm)}")
                    for fl in failed_llm[-3:]:
                        lines.append(f"  - {fl.strip()[:100]}")
        except Exception:
            pass

    return "\n".join(lines) + "\n"


def gen_chief() -> str:
    """Generate 'Chief.md' — Chief status dashboard."""
    procs = get_processes()
    chief_procs = procs.get("chief", [])

    lines = [
        "# 🎖️ Chief — Status Dashboard",
        f"*Updated: {now_str()}*",
        "",
        "### Processes",
    ]

    expected = [
        "chief_listener.py",
        "chief_worker.py",
        "chief_memory_worker.py",
        "chief_state_worker.py",
        "chief_watcher_brain.py",
    ]

    running_names = set()
    for p in chief_procs:
        for name in expected:
            if name in p["line"]:
                running_names.add(name)

    for name in expected:
        if name in running_names:
            lines.append(f"- ✅ {name}")
        else:
            lines.append(f"- ❌ {name} — NOT RUNNING")

    # Also show other chief processes
    others = [p for p in chief_procs if not any(e in p["line"] for e in expected)]
    if others:
        lines.append("")
        lines.append("### Other Chief Processes")
        for p in others:
            cmd = p["line"].split("/")[-1][:60] if "/" in p["line"] else p["line"][:60]
            lines.append(f"- PID {p['pid']}: `{cmd}`")

    # Builder status
    builder_procs = procs.get("builder", [])
    lines.extend(["", "### Builder"])
    if builder_procs:
        for p in builder_procs:
            lines.append(f"- ✅ PID {p['pid']}: running")
    else:
        lines.append("- ⬜ No builder process running (normal when idle)")

    # Ollama
    lines.extend(["", "### Ollama Models"])
    try:
        out = subprocess.check_output(
            ["curl", "-s", "http://localhost:11434/api/tags"],
            text=True, timeout=5
        )
        models = json.loads(out).get("models", [])
        for m in models:
            lines.append(f"- {m['name']}")
    except Exception:
        lines.append("- ❌ Ollama not reachable")

    return "\n".join(lines) + "\n"


def gen_guardian() -> str:
    """Generate 'Guardian.md' — Guardian approval dashboard."""
    procs = get_processes()
    guardian_procs = procs.get("guardian", [])
    pending = load_json(APPROVAL_PENDING)

    lines = [
        "# 🛡️ Guardian — Approval Dashboard",
        f"*Updated: {now_str()}*",
        "",
        "### Guardian Process",
    ]

    if guardian_procs:
        for p in guardian_procs:
            lines.append(f"- ✅ PID {p['pid']}: running")
    else:
        lines.append("- ❌ Guardian listener not running!")

    # Pending approvals
    lines.extend(["", "### Pending Approvals"])
    if pending and pending.get("status") == "pending":
        lines.extend([
            f"- ⏳ **Pending:** {pending.get('action', 'unknown action')}",
            f"  - Requester: {pending.get('requester', '?')}",
            f"  - Requested: {pending.get('requested_at', '?')}",
            f"  - Tier: L{pending.get('tier', '?')}",
        ])
    else:
        lines.append("- ✅ No pending approvals")

    # Approval policy summary
    lines.extend([
        "", "### Approval Tiers",
        "| Tier | Trigger | Behavior |",
        "|---|---|---|",
        "| L0 | Read-only, git, new files, vault edits | No gate |",
        "| L1 | Package installs, service restarts, config | Local y/N prompt |",
        "| L2 | Deletions, secrets, force-push, external | Phone approval via Guardian |",
    ])

    return "\n".join(lines) + "\n"


def gen_big_picture() -> str:
    """Generate 'Big Picture.md' — system-wide overview."""
    status = load_json(STATUS_FILE)
    procs = get_processes()
    flags = get_capability_flags()
    queued = get_queued_tasks()

    total_procs = sum(len(v) for v in procs.values())

    lines = [
        "# 🌐 Open Claw — Big Picture",
        f"*Updated: {now_str()}*",
        "",
        "### System Health",
    ]

    # Loop status
    state = status.get("status", "unknown")
    icon = STATUS_ICON.get(state, "❓")
    lines.append(f"- {icon} Loop: **{state}** — {STATUS_EXPLAIN.get(state, 'unknown')}")

    # Process count by subsystem
    for sub in ["cassandra", "chief", "guardian", "builder", "other"]:
        count = len(procs.get(sub, []))
        sub_icon = "✅" if count > 0 else "⬜"
        lines.append(f"- {sub_icon} {sub.title()}: {count} process{'es' if count != 1 else ''}")

    lines.append(f"- 📊 Total: {total_procs} processes")

    # Budget
    lines.extend(["", "### Budget"])
    budget = get_budget_status()
    for bline in budget.splitlines()[:5]:
        lines.append(f"  {bline}")

    # Capabilities summary
    connected = sum(1 for v in flags.values() if v)
    total = len(flags)
    lines.extend([
        "", f"### Cassandra Capabilities ({connected}/{total} connected)",
    ])
    for name, val in sorted(flags.items()):
        icon = "✅" if val else "❌"
        lines.append(f"- {icon} {name}")

    # Task queue
    lines.extend([
        "", f"### Task Queue ({len(queued)} waiting, {get_archive_count()} completed)",
    ])
    for t in queued[:8]:
        lines.append(f"- {t}")
    if len(queued) > 8:
        lines.append(f"- ... {len(queued) - 8} more")

    # Runners
    lines.extend(["", "### Runners"])
    try:
        out = subprocess.check_output(
            ["python3", "/home/openclaw/runner_registry.py", "--json"],
            text=True, timeout=5, cwd="/home/openclaw"
        )
        runners = json.loads(out)
        for r in runners:
            name = r.get("name", "?")
            host = r.get("host", "?")
            cost = r.get("cost_tier", "?")
            lines.append(f"- {name} ({host}, {cost})")
    except Exception:
        lines.append("  (runner registry unavailable)")

    # Manual action items
    action_items = []
    nicknames = load_json(CONTACT_NICKNAMES)
    has_placeholders = any(
        "PLACEHOLDER" in str(v)
        for k, v in nicknames.items()
        if not k.startswith("_")
    )
    if has_placeholders:
        action_items.append("Fill in contact_nicknames.json with real names")

    pending = load_json(APPROVAL_PENDING)
    if pending and pending.get("status") == "pending":
        action_items.append(f"Pending approval: {pending.get('action', '?')[:60]}")

    if status.get("block_reason"):
        action_items.append(f"Loop blocked: {status['block_reason']}")

    not_connected = [k for k, v in flags.items() if not v]
    if not_connected:
        action_items.append(f"{len(not_connected)} capabilities not connected: {', '.join(not_connected)}")

    if action_items:
        lines.extend(["", "### ⚠️ Action Items"])
        for item in action_items:
            lines.append(f"- {item}")
    else:
        lines.extend(["", "### ✅ No action items — system healthy"])

    return "\n".join(lines) + "\n"


def run_autonomy_qual():
    """Run autonomy_qualification.py to update Autonomy Qualification.md."""
    try:
        subprocess.run(
            ["python3", str(AUTONOMY_QUAL)],
            timeout=15, cwd="/home/openclaw",
            capture_output=True
        )
    except Exception:
        pass


def auto_queue_system_tasks():
    """Detect common system issues and auto-queue fix tasks if not already queued."""
    existing = set(get_queued_tasks())
    status = load_json(STATUS_FILE)

    # Only auto-queue when loop is idle
    if status.get("status") != "idle":
        return

    # Check for disconnected capabilities that have no queued task
    flags = get_capability_flags()
    cap_task_map = {
        "FILE_VERIFY_CONNECTED": ("cas-fix-file-verify", "Wire FILE_VERIFY capability so Cassandra can check file existence"),
        "FUTURE_ACTION_CONNECTED": ("cas-fix-future-action", "Wire FUTURE_ACTION capability so Cassandra can schedule follow-ups"),
        "PII_VAULT_CONNECTED": ("cas-fix-pii-vault", "Activate PII vault — generate key and connect to Cassandra"),
    }

    for flag, (prefix, goal) in cap_task_map.items():
        if flags.get(flag, True):  # skip if already connected
            continue
        # Check if any task with this prefix already exists
        if any(t.startswith(prefix) or t.startswith(f"cas-upgrade-{flag.lower().replace('_connected','')}") for t in existing):
            continue
        # Don't create if it was recently archived
        try:
            archived = [p.stem for p in ARCHIVE_DIR.glob(f"*{prefix}*")]
            if archived:
                continue
        except Exception:
            pass

    # Note: PAYMENT_EXTERNAL requires an architecture decision, don't auto-queue


# ── Main loop ─────────────────────────────────────────────────────────────────

def write_dashboard(path: Path, content: str):
    """Write content to file atomically."""
    tmp = path.with_suffix(".tmp")
    tmp.write_text(content, encoding="utf-8")
    tmp.rename(path)


def main():
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    print(f"[{now_str()}] Dashboard generator started — writing to {OUT_DIR}", flush=True)

    while True:
        try:
            write_dashboard(OUT_DIR / "For Winship 1 - Right Now.md", gen_right_now())
            write_dashboard(OUT_DIR / "For Winship 2 - What Happened.md", gen_what_happened())
            write_dashboard(OUT_DIR / "Cassandra.md", gen_cassandra())
            write_dashboard(OUT_DIR / "Chief.md", gen_chief())
            write_dashboard(OUT_DIR / "Guardian.md", gen_guardian())
            write_dashboard(OUT_DIR / "Big Picture.md", gen_big_picture())
            run_autonomy_qual()
        except Exception as exc:
            print(f"[{now_str()}] Error generating dashboards: {exc}", flush=True)

        time.sleep(INTERVAL)


if __name__ == "__main__":
    main()
