#!/usr/bin/env bash
set -euo pipefail

# sync_to_mac.sh — Push review-only files from PC truth to Mac-local folder.
#
# Runs on the PC (WSL). Uses rsync over SSH to mirror the review set
# into a Mac-local directory that VS Code can open without Remote-SSH.
#
# Usage:
#   ./sync_to_mac.sh              # one-shot sync
#   ./sync_to_mac.sh --watch      # continuous sync every 30s (matches dashboard_gen interval)
#
# Prerequisites:
#   - Mac reachable from WSL via: ssh mac (configure in ~/.ssh/config)
#   - rsync installed on both sides
#   - Mac target directory will be created automatically

# ── Config ────────────────────────────────────────────────────────────────────

SSH_HOST="mac"                                        # Mac SSH alias (see ~/.ssh/config)
MAC_DIR="~/OpenClaw_Watch"                            # Mac-local review folder
PC_SOURCE="/home/openclaw/mac_eyes/Winship"           # PC truth (generated by dashboard_gen.py)
INTERVAL=30                                           # seconds between syncs in --watch mode
CANONICAL_DOCS_ROOT="/home/openclaw/docs"             # Canonical docs root
MIRROR_STATUS_FILE="Mirror Freshness.md"              # Mac-local mirror freshness marker

# ── Review set (only these files are mirrored) ────────────────────────────────

REVIEW_FILES=(
  "Live Watch.md"
  "Right now.md"
  "Builder Right now.md"
  "Planner Right now.md"
  "Deep Dive Report.md"
  "What happened.md"
  "Mac Local AI Watch — READ ME.md"
  "Mac Local AI Watch.code-workspace"
)

# ── Sync function ─────────────────────────────────────────────────────────────

do_sync() {
  # Ensure Mac target dir exists
  ssh "$SSH_HOST" "mkdir -p $MAC_DIR" 2>/dev/null || true

  local synced=0
  for f in "${REVIEW_FILES[@]}"; do
    src="$PC_SOURCE/$f"
    if [[ -f "$src" ]]; then
      rsync -az --timeout=10 "$src" "$SSH_HOST:$MAC_DIR/" 2>/dev/null && ((synced++)) || true
    fi
  done

  local status_tmp
  status_tmp="$(mktemp)"
  cat > "$status_tmp" <<EOF
# Mirror Freshness

- Source path: \`$PC_SOURCE\`
- Canonical docs root: \`$CANONICAL_DOCS_ROOT\`
- Last sync time: \`$(date '+%Y-%m-%d %H:%M:%S %Z')\`
- Files copied this run: \`$synced/${#REVIEW_FILES[@]}\`
- Warning: This mirror is a non-canonical reflection layer. Confirm against canonical docs and runtime-derived evidence before treating it as current truth.
EOF
  rsync -az --timeout=10 "$status_tmp" "$SSH_HOST:$MAC_DIR/$MIRROR_STATUS_FILE" 2>/dev/null || true
  rm -f "$status_tmp"

  echo "[$(date '+%H:%M:%S')] synced $synced/${#REVIEW_FILES[@]} files to $SSH_HOST:$MAC_DIR"
}

# ── Main ──────────────────────────────────────────────────────────────────────

if [[ "${1:-}" == "--watch" ]]; then
  echo "sync_to_mac: watching every ${INTERVAL}s  (Ctrl-C to stop)"
  while true; do
    do_sync
    sleep "$INTERVAL"
  done
else
  do_sync
fi
