#!/usr/bin/env python3
"""Generate invoice_proof_artifacts.json from REAL produced invoice artifacts on disk.

This is the "the system documents what it produced + where it lives" step for finance/proof
artifacts. It SCANS the produced-artifact tree for gig folders that contain a `gig_facts.json`
plus a branded invoice PDF, and emits a deterministic registry keyed by context so a consumer
(the Mission Control "show me the proof" intent) can resolve the real PDF instead of guessing.

Anti-snow-globe: every entry is generated from a real file on disk (real path + real sha256);
nothing is hand-authored. Metadata + body-sha256 of the explicit produced artifact only — no
broad scan, no body ingest of anything else, no send, no mutation.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path
from typing import Any

SCHEMA_VERSION = "invoice_proof_artifacts_v0"
MAC_ROOT = "/Volumes/openclaw_e"
BRIDGE_ROOT = "/mnt/e/openclaw"

# Produced-artifact roots to scan. Mac (share-mounted) path first; the bridge path is derived.
DEFAULT_ARTIFACTS_ROOTS = (
    f"{MAC_ROOT}/orchestration/artifacts",
    f"{MAC_ROOT}/artifacts",
)

DEFAULT_INTENTS = [
    "show me the proof",
    "show the invoice",
    "show me the invoice",
    "pull up the invoice",
    "proof",
]


def _bridge_path(mac_path: str) -> str:
    if mac_path.startswith(MAC_ROOT):
        return BRIDGE_ROOT + mac_path[len(MAC_ROOT):]
    return mac_path


def _sha256(path: Path) -> str:
    return "sha256:" + hashlib.sha256(path.read_bytes()).hexdigest()


def _client_ref(name: str) -> str:
    out = "".join(c if (c.isalnum() or c == " ") else "" for c in name.strip().lower())
    return "_".join(out.split())


def artifact_from_gig_dir(gig_dir: Path) -> dict[str, Any] | None:
    """Build one registry entry from a gig folder, or None if it isn't a produced-invoice folder."""
    facts_path = gig_dir / "gig_facts.json"
    if not facts_path.is_file():
        return None
    try:
        facts = json.loads(facts_path.read_text())
    except (json.JSONDecodeError, OSError):
        return None

    pdfs = sorted(gig_dir.glob("*invoice*.pdf")) or sorted(gig_dir.glob("*.pdf"))
    if not pdfs:
        return None
    pdf = pdfs[0]

    gig = facts.get("gig", {}) if isinstance(facts.get("gig"), dict) else {}
    venue = gig.get("venue_name") or gig_dir.name
    client = _client_ref(venue)
    gig_date = gig.get("date", "")
    amount = gig.get("fee_amount", "")
    currency = gig.get("currency", "USD")
    mac_path = str(pdf)

    return {
        "artifact_ref": f"artifact:{client}_{gig_date}_invoice_pdf",
        "kind": "branded_invoice_pdf",
        "provenance": "openclaw_produced",
        "label": f"{venue} invoice — ${amount}, {gig_date}",
        "world_ref": "finance",
        "thread_ref": client,
        "client_ref": client,
        "client_display": venue,
        "gig_date": gig_date,
        "amount": amount,
        "currency": currency,
        "mac_artifact_path": mac_path,
        "bridge_path": _bridge_path(mac_path),
        "sha256": _sha256(pdf),
        "size_bytes": pdf.stat().st_size,
        "path_exists": True,
        "source_context_ref": _bridge_path(str(facts_path)),
        "authority_boundary": {
            "sent": False,
            "paid": False,
            "email_send_allowed": False,
            "outward_action_allowed": False,
        },
        "resolve_on_intents": list(DEFAULT_INTENTS),
    }


def build_invoice_proof_artifacts(*, roots: tuple[str, ...] | list[str] | None = None) -> dict[str, Any]:
    """Scan the produced-artifact roots and return the deterministic registry read-model."""
    scan_roots = list(roots) if roots is not None else list(DEFAULT_ARTIFACTS_ROOTS)
    artifacts: list[dict[str, Any]] = []
    for root_str in scan_roots:
        root = Path(root_str)
        if not root.is_dir():
            continue
        for gig_dir in sorted(p for p in root.iterdir() if p.is_dir()):
            entry = artifact_from_gig_dir(gig_dir)
            if entry is not None:
                artifacts.append(entry)

    # Deterministic order; the most recent gig_date is the active invoice.
    artifacts.sort(key=lambda a: (a.get("gig_date", ""), a.get("artifact_ref", "")))
    for entry in artifacts:
        entry["is_active_invoice"] = False
    if artifacts:
        artifacts[-1]["is_active_invoice"] = True

    return {
        "schema_version": SCHEMA_VERSION,
        "note": (
            "Registry of REAL produced invoice/proof artifacts so any consumer (Mission Control "
            "'show me the proof', Cassandra) resolves them by context. GENERATED by "
            "scripts/build_invoice_proof_artifacts.py scanning produced-artifact folders on disk — "
            "not hand-authored. Registering a proof is SEND_HOLD-neutral: it never sends or pays."
        ),
        "provenance_policy": "every entry is generated from a real file on disk (real path + real sha256)",
        "path_mapping": {
            "bridge_root": BRIDGE_ROOT,
            "mac_root": MAC_ROOT,
            "rule": "a bridge_path under /mnt/e/openclaw maps to /Volumes/openclaw_e on the Mac",
        },
        "artifact_count": len(artifacts),
        "artifacts": artifacts,
    }


def stable_json(payload: dict[str, Any]) -> str:
    return json.dumps(payload, indent=2, sort_keys=True) + "\n"


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate invoice_proof_artifacts.json from real produced invoice artifacts."
    )
    parser.add_argument("--format", choices=("json",), default="json", help="Output format.")
    parser.add_argument(
        "--write",
        metavar="PATH",
        default=None,
        help="If set, write the registry JSON to PATH (e.g. the generated/read_models target).",
    )
    parser.add_argument(
        "--root",
        action="append",
        default=None,
        help="Override produced-artifact scan root (repeatable). Defaults to the share artifact roots.",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(sys.argv[1:] if argv is None else argv)
    read_model = build_invoice_proof_artifacts(roots=args.root)
    rendered = stable_json(read_model)
    if args.write:
        Path(args.write).write_text(rendered)
        print(f"wrote {read_model['artifact_count']} artifact(s) -> {args.write}")
    else:
        print(rendered, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
