#!/usr/bin/env python3
"""Generate Hermes's OpenClaw inventory from the business-ops ledger."""

from __future__ import annotations

import argparse
import sqlite3
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from business_ops_ledger import resolve_business_ops_ledger_path


def _connect(path: str | Path) -> sqlite3.Connection:
    conn = sqlite3.connect(path)
    conn.row_factory = sqlite3.Row
    return conn


def _table_exists(conn: sqlite3.Connection, table_name: str) -> bool:
    return conn.execute(
        "SELECT 1 FROM sqlite_master WHERE type='table' AND name=?",
        (table_name,),
    ).fetchone() is not None


def _rows(conn: sqlite3.Connection, sql: str, params: tuple[Any, ...] = ()) -> list[sqlite3.Row]:
    try:
        return list(conn.execute(sql, params).fetchall())
    except sqlite3.Error:
        return []


def _count(conn: sqlite3.Connection, table: str) -> int:
    if not _table_exists(conn, table):
        return 0
    try:
        return int(conn.execute(f"SELECT count(*) FROM {table}").fetchone()[0])
    except sqlite3.Error:
        return 0


def _safe(value: Any) -> str:
    text = " ".join(str(value or "").split())
    return text if text else "unknown"


def build_hermes_inventory_markdown(*, ledger_path: str | Path | None = None) -> str:
    ledger = Path(resolve_business_ops_ledger_path(ledger_path)).resolve(strict=False)
    conn = _connect(ledger)
    try:
        table_counts = {
            "corpus_paths": _count(conn, "corpus_paths"),
            "file_inventory": _count(conn, "file_inventory"),
            "canonical_facts": _count(conn, "canonical_facts"),
            "agent_runtime_components": _count(conn, "agent_runtime_components"),
            "agent_lanes": _count(conn, "agent_lanes"),
            "module_registry_modules": _count(conn, "module_registry_modules"),
            "context_packet_items": _count(conn, "context_packet_items"),
        }
        agents = _rows(
            conn,
            """
            SELECT agent_id, display_name, lane_id, status, authority_level, role_summary
            FROM agent_lanes
            ORDER BY agent_id
            LIMIT 12
            """,
        ) if _table_exists(conn, "agent_lanes") else []
        roots = _rows(
            conn,
            """
            SELECT root_id, COALESCE(repo_name, root_label, root_id) AS name,
                   absolute_root, COALESCE(canonical_status, status, '') AS status,
                   COALESCE(updated_at, created_at, '') AS updated_at
            FROM corpus_roots
            ORDER BY root_id
            LIMIT 16
            """,
        ) if _table_exists(conn, "corpus_roots") else []
        modules = _rows(
            conn,
            """
            SELECT module_id, COALESCE(display_name, name, module_id) AS name,
                   status, authority_level, description
            FROM module_registry_modules
            ORDER BY module_id
            LIMIT 16
            """,
        ) if _table_exists(conn, "module_registry_modules") else []
    finally:
        conn.close()

    lines = [
        "# OpenClaw Inventory - generated from the business-ops ledger",
        "",
        "You are Hermes, OpenClaw's advisory systems engineer. OpenClaw is not a blank slate.",
        "Use the business-ops ledger as the durable source of truth for system inventory,",
        "agent lanes, indexed files, modules, and canonical facts. Propose improvements by",
        "referencing real components and the real gap; do not suggest generic SaaS replacements.",
        "",
        "## Source Of Truth",
        f"- Ledger: `{ledger}`",
        "- Generated by: `scripts/export_hermes_inventory_from_ledger.py`",
        "- Authority: read-only inventory for advisory grounding; no sends, money movement,",
        "  ledger mutation, agent dispatch, or approval decisions are granted here.",
        "",
        "## Ledger Counts",
    ]
    for table, count in table_counts.items():
        lines.append(f"- `{table}`: {count}")

    lines.extend(["", "## Agents"])
    if agents:
        for row in agents:
            lines.append(
                f"- **{_safe(row['display_name'])}** (`{_safe(row['agent_id'])}`) - "
                f"lane `{_safe(row['lane_id'])}`, status `{_safe(row['status'])}`, "
                f"authority `{_safe(row['authority_level'])}`. {_safe(row['role_summary'])}"
            )
    else:
        lines.append("- No agent lane rows found in the ledger.")

    lines.extend(["", "## Repositories And Roots"])
    if roots:
        for row in roots:
            lines.append(
                f"- `{_safe(row['root_id'])}` - {_safe(row['name'])}: "
                f"`{_safe(row['absolute_root'])}` ({_safe(row['status'])})"
            )
    else:
        lines.append("- No corpus root rows found in the ledger.")

    lines.extend(["", "## System Modules"])
    if modules:
        for row in modules:
            lines.append(
                f"- **{_safe(row['name'])}** (`{_safe(row['module_id'])}`) - "
                f"status `{_safe(row['status'])}`, authority `{_safe(row['authority_level'])}`. "
                f"{_safe(row['description'])}"
            )
    else:
        lines.append("- No module registry rows found in the ledger.")

    lines.extend(
        [
            "",
            "## Operating Guidance",
            "- Treat ledger-backed packet facts as the grounding layer.",
            "- Treat operational queues and finance execution stores as separate concerns unless",
            "  a task explicitly grants authority and Guardian/operator approval exists.",
            "- Missing ledger evidence is a data gap, not permission to invent state.",
            "- For build work, route through the existing Chief/Guardian-governed package path.",
            "",
        ]
    )
    return "\n".join(lines)


def export_hermes_inventory(
    *,
    ledger_path: str | Path | None = None,
    output_path: str | Path = "sidecars/hermes_home/OPENCLAW_INVENTORY.md",
) -> dict[str, Any]:
    output = Path(output_path)
    output.parent.mkdir(parents=True, exist_ok=True)
    text = build_hermes_inventory_markdown(ledger_path=ledger_path)
    output.write_text(text, encoding="utf-8")
    return {
        "status": "written",
        "output_path": str(output),
        "ledger_path": str(Path(resolve_business_ops_ledger_path(ledger_path)).resolve(strict=False)),
        "bytes": len(text.encode("utf-8")),
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--ledger", default=None)
    parser.add_argument("--output", default="sidecars/hermes_home/OPENCLAW_INVENTORY.md")
    args = parser.parse_args()
    result = export_hermes_inventory(ledger_path=args.ledger, output_path=args.output)
    print(f"wrote {result['output_path']} from {result['ledger_path']} ({result['bytes']} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
